EE_LIB_NAME = librac1ntscj.a
EE_DEFS = -DRAC1_NTSCJ -DRAC_NTSCJ -DNTSCJ -DRAC1_V100 -DRAC_V100 -DRAC1_NTSCJ_V100

include ${CURDIR}/Makefile.defs
include $(PS2SDK)/samples/Makefile.pref
include ${CURDIR}/Makefile.eeglobal
