EE_LIB_NAME = librac1pal.a
EE_DEFS = -DRAC1_PAL -DRAC_PAL -DPAL -DRAC1_V100 -DRAC_V100 -DRAC_PAL_V100 -DRAC1_PAL_V100

include ${CURDIR}/Makefile.defs
include $(PS2SDK)/samples/Makefile.pref
include ${CURDIR}/Makefile.eeglobal
