#ifndef _LIBRAC1_GADGET_H_
#define _LIBRAC1_GADGET_H_

#include "types.h"

typedef enum GADGET_IDS {
    GADGET_ID_NONE = 0,
    GADGET_ID_WRENCH = 8,
    GADGET_ID_SUCK_CANNON = 9,
    GADGET_ID_BOMB_GLOVE = 10,
    GADGET_ID_DEVASTATOR = 11,
    GADGET_ID_SWINGSHOT = 12,
    GADGET_ID_VISIBOMB_GUN = 13,
    GADGET_ID_TAUNTER = 14,
    GADGET_ID_BLASTER = 15,
    GADGET_ID_PYROCITOR = 16,
    GADGET_ID_MINE_GLOVE = 17,
    GADGET_ID_WALLOPER = 18,
    GADGET_ID_TESLA_CLAW = 19,
    GADGET_ID_GLOVE_OF_DOOM = 20,
    GADGET_ID_MORPH_O_RAY = 21,
    GADGET_ID_HYDRODISPLACER = 22,
    GADGET_ID_RYNO = 23,
    GADGET_ID_24 = 24,
    GADGET_ID_DECOY_GLOVE = 25,
    GADGET_ID_TRESPASSER = 26,
    GADGET_ID_PDA = 32,
} eGADGET_IDS;

#endif // _LIBRAC1_GADGET_H_
